### ISSUE TITLE
Conditional: AverageLight comparison

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#100]
**Syntax:** _$entity.averagelight.#radius.$comparison.#value_

**Description:** Returns true if the comparison to the average light in the specified area around the specified entity is true.

**Example:**

``` yaml
Food: #No bad Mogwai kthx.
    - 'if event.time.greaterthan.16000 and target.group.Mogwai and target.averagelight.2.lessthanequals.4':
        - 'targeteffect.explode': '2'
        - 'message.world._mogwaiWarning'
Aliases:
    Message:
        - "Noo! Don't feed them past midnight!"
```

See also: [World Time](https://github.com/KoryuObihiro/ModDamage/wiki/Statement:-World-Time), [Group](https://github.com/KoryuObihiro/ModDamage/wiki/Statement:-Group), [Explode](https://github.com/KoryuObihiro/ModDamage/wiki/Effect:-Explode), [Message](https://github.com/KoryuObihiro/ModDamage/wiki/Routine:-Message)

_Technical notes: Grab only light of AIR blocks?_
