### ISSUE TITLE
Make Calculations have ML-type inputs?

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#104]
Example:

``` yaml
'$entity.setvelocity':
    x: 'routine'
    y: 'routine'
    z: 'routine'
```
