### ISSUE TITLE
EntitySpawn Calculation

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#105]
**Syntax:** _$entityeffect.spawn.$livingelement_

**Description**: Spawns creature(s) in the quantity specified by the returned integer, at the specified entity's location.

**Example:**

``` yaml
Death: #Zombie kills yield more zombies. 
    - 'if attacker.type.Zombie and target.type.Human':
        - 'targeteffect.spawn.Zombie': '1'
```

Originally suggested by [Ranzear](http://forums.bukkit.org/members/ranzear.67370/).
