### ISSUE TITLE
DelayedRoutine routine

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#119]
**Syntax:** _delay.#(1/20)seconds_

**Description:** Exposes access to the scheduling of a single task - in English, this lets you make delayed effects, though it should be kept in mind you can't change an event after it's already occurred. Use with caution.

**Example:**

``` yaml
Damage: #Give Admin TNT punches an exciting twist.
    - 'if attacker.group.Admins and attacker.wielding.TNT and target.type.Player':
        - "message.target.You've been TNT-slapped! Get ready to explode!"
        - 'delay.2000':
            - 'message.world.5'
        - 'delay.3000':
            - 'message.world.4'
        - 'delay.4000':
            - 'message.world.3'
        - 'delay.5000':
            - 'message.world.2'
        - 'delay.6000':
            - 'message.world.1'
        - 'delay.7000':
            - 'targeteffect.explode': '5'
```

See also: [Binomial](https://github.com/KoryuObihiro/ModDamage/wiki/Statement:-Binomial)
