### ISSUE TITLE
Permission conditional

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#121]
**Syntax:** _$entity.haspermission.$permissionstring_

**Description:** Checks whether the player has permission using an integrated Perms plugin or SuperPerms when none has been found.

**Example:**

``` yaml
Damage: #Give those with the right perms a boost.
    - 'if attacker.haspermission.moddamage.moredamage':
        - 'mult.2'
```

Syntax for this conditional is open for feedback, since I personally think it doesn't look pretty.
