### ISSUE TITLE
Damage reduction, no effect

### ISSUE THREAD

**Issue by Brvtvs** [ModDamage/ModDamage#129]
``` yaml
Aliases:
    Item:
        pickaxe:
        - WOOD_PICKAXE
        - STONE_PICKAXE
        - IRON_PICKAXE
        - GOLD_PICKAXE
        - DIAMOND_PICKAXE
        spade:
        - WOOD_SPADE
        - STONE_SPADE
        - IRON_SPADE
        - GOLD_SPADE
        - DIAMOND_SPADE
        hoe:
        - WOOD_HOE
        - STONE_HOE
        - IRON_HOE
        - GOLD_HOE
        - DIAMOND_HOE
        axe:
        - WOOD_AXE
        - STONE_AXE
        - IRON_AXE
        - GOLD_AXE
        - DIAMOND_AXE
        sword:
        - WOOD_SWORD
        - STONE_SWORD
        - IRON_SWORD
        - GOLD_SWORD
        - DIAMOND_SWORD
Damage:
    - 'if target.group.donator1':
        - 'mult.90'
        - 'div.100'
    - 'if target.group.donator2':
        - 'mult.85'
        - 'div.100'
    - 'if target.group.donator3':
        - 'mult.80'
        - 'div.100'
    - 'if target.group.donator4':
        - 'mult.70'
        - 'div.100'
Death:
Food:
debugging: Verbose
Spawn:
```

EDIT: Sorry I forgot my PEX setup.

``` yaml
groups:
    default:
        default: true
        permissions:
        - essentials.warp.initial
        - essentials.warp
        - multiverse.portal.access.*
        - factions.viewAnyPower
        - factions.participate
        - essentials.msg
        - essentials.help
        - essentials.ignore
        - essentials.list
        - essentials.me
        - essentials.motd
        - essentials.rules
        - essentials.whois
        - essentials.spawn
        - commandsigns.use.*
        - democracy.vote.vote
        - iConomy.holdings
        - iConomy.help
        - iConomy.payment
        suffix: ':'
        options:
            rank: '1000'
    donator1:
        default: false
        inheritance:
        - default
        permissions:
        - essentials.warp
        - essentials.kit
        - essentials.kit.build
        prefix: '&6'
        suffix: '&f:'
        options:
            rank: '800'
    donator2:
        default: false
        inheritance:
        - default
        permissions:
        - essentials.warp
        - essentials.warp.initial
        - essentials.kit
        - essentials.kit.tools
        - essentials.kit.build
        prefix: '&6'
        suffix: '&f:'
        options:
            rank: '700'
    donator3:
        default: false
        inheritance:
        - default
        permissions:
        - essentials.warp
        - essentials.kit
        - essentials.kit.weapons
        - essentials.kit.build
        - essentials.kit.tools
        - herosneak.sneak
        prefix: '[&6Hero&f] &6'
        suffix: '&f:'
        options:
            rank: '500'
    donator4:
        default: false
        inheritance:
        - default
        permissions:
        - essentials.warp
        - essentials.kit
        - essentials.kit.weapons
        - essentials.kit.build
        - essentials.kit.tools
        - herosneak.sneak
        prefix: '[&6Hero&f] &6'
        suffix: '&f:'
        options:
            rank: '500'
            rank-ladder: '400'
    mod:
        default: false
        inheritance:
        - default
        permissions:
        - essentials.ban
        - essentials.notify
        - essentials.offline
        - essentials.banip
        - essentials.broadcast
        - essentials.togglejail
        - essentials.togglejail.offline
        - essentials.mute
        - essentials.mute.exempt
        - essentials.tempban
        - essentials.tempbanexempt
        - essentials.kick
        - essentials.jails
        - essentials.kick.notify
        - essentials.kick.exempt
        prefix: '[&9Moderator&f] '
        suffix: :&9
        options:
            rank: '100'
    dev:
        default: false
        permissions:
        - '*'
        prefix: '[&4Developer&f] '
        suffix: :&c
        options:
            rank: '0'
    admin:
        default: false
        permissions:
        - '*'
        prefix: '[&cAdmin&f]&f '
        suffix: :&c
        options:
            rank: '0'
        worlds:
            test:
                prefix: set
```
