### ISSUE TITLE
Associate int values with tags?

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#136]
This might be potentially sticky, but with the proposal of a Time event (issue #135) it might be nice to associate values with tags. It'd also make things like the [timebomb example in the Explode Calculation](https://github.com/KoryuObihiro/ModDamage/wiki/Calculation:-Explode) simpler.

Examples:

``` yaml
Aliases: 
    Routine:
        makeEmExplode:
            - 'switch.condition':
                - 'if target.tagvalue_explosive.lessthanequals.0':
                    - 'targeteffect.explode': '40'
                - 'true':
                    - 'setvariable.temp': 'target.tagvalue_explosive'
                    - 'message.target.&e%event.value%'
                    - 'if variable.temp.equals.2 and target.type.player':
                        - "message.world.&2Run for it! &7%target.name%&2's gonna blow!"
                    - 'tag.target.explosive.(variable.temp - 1)'
                    - 'delay.20': '_makeEmExplode'
Damage:
    - 'if attacker.type.player and projectile.type.arrow and attacker.haspermission.magicarrows':
        - "message.attacker.&6Plugged 'em with a bit o' magic. :3"
        - 'tag.target.explosive.10'
        - '_makeEmExplode'
```

``` yaml
Damage:
    - 'if attacker.group._cursedOne and target.type.player':
        - 'tag.target.cursed.4'
Time:
    - 'if target.istagged.cursed':
        - 'tag.target.cursed.(target.tagvalue_cursed - 1)'
```

This also refers to issue #92, which allows for variable setting.
