### ISSUE TITLE
Override Type/Element names manually

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#139]
Already implemented at time of writing, just needs preliminary testing.

This feature will allow dynamic Type strings to be overriden in an easy fashion. Example would be like so:

``` yaml
Aliases:
    TypeName:
        Zombie:
            - 'DEAD1'
            - 'DEAD2'
            - 'DEAD3'
Death:
    - 'if attacker.type.zombie and target.type.player': 'message.world.Oh dear....another %target.type% was killed by a %attacker.type%
```

This example could display "Oh dear...another PLAYER was killed by a DEAD{1,2,3}"
