### ISSUE TITLE
Comma-separated lists for multi-value aliasables

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#143]
Probably should be strict about the whitespace, but something like this should be easy to implement and a nice thing to have when one doesn't want to set up an alias for situations like this:

``` yaml:
Damage:
    - 'switch.attacker.wielding':
         - 'IRON_INGOT,GOLD_INGOT':
    [. . .]
         - 'REDSTONE_DUST,DIAMOND,GOLD_NUGGET':
    [. . .]
         -'GOLD_SWORD,IRON_SWORD':
    [. . .]
```
