### ISSUE TITLE
Issue with attacker.wielding

### ISSUE THREAD

**Issue by SwarmOfBees** [ModDamage/ModDamage#167]
build #292, 
offending code: 

``` yaml
Damage:
    - 'switch.attacker.type':
        - 'PLAYER':
            - 'message.attacker': '%{attacker_wielding}'
            - '0'
            - 'switch.attacker.wielding': #Weapons
                - 'AIR':
                    - '+range(1,2)'
                    - 'message.attacker': "&dUNARMED"
```

messages are debug messages, the first one returns AIR when I punch something unarmed (http://i.imgur.com/oDrB5.png), but the 'AIR' case in my wielding switch is ignored, so the damage is never set and I never see the second debug message
