### ISSUE TITLE
Only one item-specific is loading.

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#28]
Given the following config:

```
Offensive:
    WorldName:
        global:
            item:
                GOLD_AXE:
                    - 'set.0'
                GOLD_SWORD:
                    - 'set.1'
```

Only GOLD_SWORD loads with the correct information. GIT 'ER DONE
