### ISSUE TITLE
Item aliasing

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#56]
The goal is basically to get rid of the hardcoded enumerations for "sword", "hoe", "pickaxe", etc. and to replace it with something very dynamic, which the user can define. Consider the following:

``` yaml
 Damage:
    - 'if.attackerwielding._diamondtools':
        - 'set.20'

Aliases:
    item:
        diamondtools:
            - 'diamond_sword'
            - 'diamond_hoe'
            - 'diamond_axe'
            - 'diamond_pickaxe'
            - 'diamond_spade'
```

The only possible conflicts would be multiple aliases...which programmatically should be easy to handle. Just make them sequential. :P
