### ISSUE TITLE
Deprecate the Damage Elements Tree in favor of using conditionally-driven configuration.

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#62]
Since group, mob type, etc. can be evaluated easily with conditionals now, it's more than feasible to deprecate the DET in favor of something more intuitive and user-friendly, which can be illustrated with the following example:

Old DET config:

``` yaml
Offensive:
    global:
        generic:
            humans:
                - '-2'
        mob:
            Slime:
                - 'binom.80'
    worlds:
        zoo:
            generic:
                humans:
                    - 'if.attackeris.onfire':
                        - 'set.0'
                mob:
                    - 'if.attackeris.onfire':
                        - 'set.0'
                animal:
                    - 'if.attackeris.onfire':
                        - 'set.0'

```

Conditional config:

``` yaml
Damage:
    global:
        - 'switch.attackertype':
            - 'human':
                - '-2'
            - 'Slime':
                - 'binom.80'
    worlds:
        zoo:
            - 'if.attackeris.onfire':
                - 'set.0'
```

This should eliminate seemingly abundant confusion that users new to MD have when attempting to configure what is currently Offensive/Defensive damage configuration, and should overall simplify the configuration process.
