### ISSUE TITLE
Mob/player tagging (dynamic aliasing)

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#67]
An idea that [lucent](http://forums.bukkit.org/members/lucent.77120/) made me think of.

Dynamically add entities to aliases ingame?! :D

0.9.4:

``` yaml
Offensive:
    global:
        melee:
            - 'binom.10':
                - 'targeteffect.tag.FragileSkeleton'
Defensive:
    global:
        mob:
            _FragileSkeleton: #We would denote a label with an underscore, for various reasons.
                   - '8'
```

0.9.5:

``` yaml
Damage:
    - 'switch.targettype.mob':
        - '_FragileSkeleton':
            - '8'
        - 'Skeleton':
            - 'binom.10':
                - 'targettag.FragileSkeleton'
```

Perhaps a mobspawn-type command could be added, too?! "/spawn _bigboss"
