### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#92]
OLD:
Use this to keep track of (not so) random variables. Also, this would streamline some routine syntax so that semantics could be carried flexibly to other events (i.e., %entity instead of %target in a Health/Food node).

NEW:

I'm repurposing this issue for the "setvariable" routines and backend. Basically, the end usage should be this:

``` yaml
Damage:
    - 'setvariable.somethingcomplicated': '(target.health - 1) + 2 * 2 * 2 * 2'
    - 'message.world':
        - 'Herro, my name is Bleh.'
        - 'Today's random number is %variable.somethingcomplicated%.'
        - 'Adding 1 to it results in %(variable.somethingcomplicated + 1)%'
```
